# Generated by Django 4.2.1 on 2023-07-24 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0002_likerecord_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('pin', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='likerecord',
            unique_together={('pin', 'user')},
        ),
    ]
